version: "3.7"

services:
  onlogs:
    image: devforth/onlogs
    container_name: ${COMPOSE_PROJECT_NAME}-onlogs
    restart: always
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    ports:
      - 2874:2874
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /etc/hostname:/etc/hostname
      - onlogs:/leveldb

volumes:
  onlogs:
