services:
  db:
    image: mysql:8.0.33
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env
    healthcheck:
      test: mysqladmin ping -u  $${MYSQL_USER:-root} --password=$${MYSQL_ROOT_PASSWORD:-root}
      start_period: 5s
      interval: 5s
      timeout: 1s
      retries: 30

    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    deploy:
      resources:
        limits:
          memory: 256M

  app:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - db.env
      - app.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  db:
  nextcloud:
