-- One login role per database. main -> MAIN, second -> SECOND.
-- Each role owns the IAM schema in its own DB; no cross-DB access.

CREATE ROLE main   LOGIN PASSWORD 'main';
CREATE ROLE second LOGIN PASSWORD 'second';

-- Drop default PUBLIC CONNECT so each DB is reachable only by its own role.
REVOKE CONNECT ON DATABASE "MAIN"   FROM PUBLIC;
REVOKE CONNECT ON DATABASE "SECOND" FROM PUBLIC;
GRANT  CONNECT ON DATABASE "MAIN"   TO main;
GRANT  CONNECT ON DATABASE "SECOND" TO second;

\connect "MAIN"
GRANT ALL ON DATABASE "MAIN" TO main;
ALTER SCHEMA "IAM" OWNER TO main;
GRANT USAGE ON SCHEMA "IAM" TO main;
GRANT ALL ON ALL TABLES    IN SCHEMA "IAM" TO main;
GRANT ALL ON ALL SEQUENCES IN SCHEMA "IAM" TO main;

\connect "SECOND"
GRANT ALL ON DATABASE "SECOND" TO second;
ALTER SCHEMA "IAM" OWNER TO second;
GRANT USAGE ON SCHEMA "IAM" TO second;
GRANT ALL ON ALL TABLES    IN SCHEMA "IAM" TO second;
GRANT ALL ON ALL SEQUENCES IN SCHEMA "IAM" TO second;
