volumes:
  data:

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9900:9000
      #- 9997:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --http-enabled
