SHELL := /bin/bash

.DEFAULT:
_recipe-list:
	@recipe=$$(grep -oE '^[a-z][a-zA-Z0-9-]+:' Makefile | tr -d ':' | \
	fzf --preview 'make --silent -n {} | head -n 5' --preview-window=50%:down); \
	[[ -n "$$recipe" ]] && make --silent $$recipe

start: stop
	docker compose --env-file ./.env up -d --wait

stop: 
	docker compose --env-file ./.env down --volumes